/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exm.vistas;

import com.exm.controladorbd.Papelerabd;
import com.exm.controladorbd.SitiosWebbd;
import com.exm.modelTables.ComunicacionVistaModelosTablas;
import com.exm.modelo.Papelera;
import com.exm.modelo.SitiosWeb;
import com.exm.utilidades.Utilidades;
import java.util.Date;
import javax.swing.JOptionPane;
import com.exm.modelTables.ModelTablePapelera;
import com.exm.modelTables.ModelTableSitiosWeb;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URISyntaxException;

/**
 *
 * @author Ordenador
 */
public class GestorSitiosWeb extends javax.swing.JFrame implements ComunicacionVistaModelosTablas {

    private Utilidades utilidades;
    private Papelera papeleraeditareliminar;
    private SitiosWeb sitioswebeditareliminar;
    private Papelerabd controladorpapelera;
    private SitiosWebbd controladorsitiosweb;
    private ModelTablePapelera modelTablePapelera;
    private ModelTableSitiosWeb modelTableSitiosWeb;

    /**
     * Creates new form GestorSitiosWeb
     */
    public GestorSitiosWeb() {
        utilidades = new Utilidades();
        controladorpapelera = new Papelerabd();
        controladorsitiosweb = new SitiosWebbd();
        modelTableSitiosWeb = new ModelTableSitiosWeb(controladorsitiosweb.ObtenerSitiosWeb(), this);
        modelTablePapelera = new ModelTablePapelera(controladorpapelera.ObtenerPapelera(), this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubmenuSalir = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreSitiosWeb = new javax.swing.JTextField();
        txtURLSitiosWeb = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnLimpiarSitiosWeb = new javax.swing.JButton();
        btnGuardarSitiosWeb = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEnviaraPapelera = new javax.swing.JButton();
        cmbBusquedaSitiosWeb = new javax.swing.JComboBox<>();
        txtBuscarSitiosWeb = new javax.swing.JTextField();
        btnBuscarSitiosWeb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtNavegador = new javax.swing.JTextField();
        btnNavegar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cmbBusquedaPapelera = new javax.swing.JComboBox<>();
        txtBusquedaPapelera = new javax.swing.JTextField();
        btnBuscarPapelera = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombrePapelera = new javax.swing.JTextField();
        txtURLPapelera = new javax.swing.JTextField();
        btnRecuperarPapelera = new javax.swing.JButton();
        btnEliminarPapelera = new javax.swing.JButton();
        btnLimpiarPapelera = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuEditar = new javax.swing.JMenu();
        jMenuAcercade = new javax.swing.JMenu();

        SubmenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SubmenuSalir.setText("Salir");
        SubmenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuSalirActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sitios Web");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Web"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("URL:");

        txtNombreSitiosWeb.setToolTipText("Ingrese el nombre con el que quiera guardarlo");
        txtNombreSitiosWeb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreSitiosWebFocusGained(evt);
            }
        });

        txtURLSitiosWeb.setToolTipText("Ingrese la dirección web");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreSitiosWeb)
                    .addComponent(txtURLSitiosWeb))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreSitiosWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtURLSitiosWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        txtNombreSitiosWeb.getAccessibleContext().setAccessibleName("");
        txtNombreSitiosWeb.getAccessibleContext().setAccessibleDescription("");

        btnLimpiarSitiosWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exm/resource/img/limpiar.png"))); // NOI18N
        btnLimpiarSitiosWeb.setText("Limpiar");
        btnLimpiarSitiosWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarSitiosWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarSitiosWebActionPerformed(evt);
            }
        });

        btnGuardarSitiosWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exm/resource/img/guardar.png"))); // NOI18N
        btnGuardarSitiosWeb.setText("Guardar");
        btnGuardarSitiosWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarSitiosWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSitiosWebActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exm/resource/img/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEnviaraPapelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exm/resource/img/papelera.png"))); // NOI18N
        btnEnviaraPapelera.setText("Enviar a Papelera");
        btnEnviaraPapelera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviaraPapelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviaraPapeleraActionPerformed(evt);
            }
        });

        cmbBusquedaSitiosWeb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "URL" }));
        cmbBusquedaSitiosWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtBuscarSitiosWeb.setToolTipText("Ingrese el dato que servirá para la búsqueda");

        btnBuscarSitiosWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exm/resource/img/buscar.png"))); // NOI18N
        btnBuscarSitiosWeb.setText("Buscar");
        btnBuscarSitiosWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarSitiosWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSitiosWebActionPerformed(evt);
            }
        });

        jTable1.setModel(modelTableSitiosWeb);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cmbBusquedaSitiosWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarSitiosWeb)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarSitiosWeb))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnLimpiarSitiosWeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addComponent(btnGuardarSitiosWeb)
                        .addGap(41, 41, 41)
                        .addComponent(btnEditar)
                        .addGap(52, 52, 52)
                        .addComponent(btnEnviaraPapelera)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarSitiosWeb)
                    .addComponent(btnGuardarSitiosWeb)
                    .addComponent(btnEditar)
                    .addComponent(btnEnviaraPapelera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBusquedaSitiosWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarSitiosWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarSitiosWeb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342))
        );

        jLabel4.setText("URL:");

        txtNavegador.setToolTipText("direcci[on web");

        btnNavegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exm/resource/img/navegar.png"))); // NOI18N
        btnNavegar.setText("Ir");
        btnNavegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavegarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtNavegador)
                        .addGap(18, 18, 18)
                        .addComponent(btnNavegar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNavegar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNavegador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sitios Web", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Papelera"));

        cmbBusquedaPapelera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "URL" }));
        cmbBusquedaPapelera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtBusquedaPapelera.setToolTipText("Este dato nos servira para la b[usqueda");

        btnBuscarPapelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exm/resource/img/buscar.png"))); // NOI18N
        btnBuscarPapelera.setText("Buscar");
        btnBuscarPapelera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPapelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPapeleraActionPerformed(evt);
            }
        });

        jTable2.setModel(modelTablePapelera);
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setText("Nombre:");

        jLabel6.setText("URL:");

        txtNombrePapelera.setEditable(false);

        txtURLPapelera.setEditable(false);

        btnRecuperarPapelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exm/resource/img/recuperar.png"))); // NOI18N
        btnRecuperarPapelera.setText("Recuperar");
        btnRecuperarPapelera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecuperarPapelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarPapeleraActionPerformed(evt);
            }
        });

        btnEliminarPapelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exm/resource/img/eliminar.png"))); // NOI18N
        btnEliminarPapelera.setText("Eliminar");
        btnEliminarPapelera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarPapelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPapeleraActionPerformed(evt);
            }
        });

        btnLimpiarPapelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exm/resource/img/limpiar.png"))); // NOI18N
        btnLimpiarPapelera.setText("Limpiar");
        btnLimpiarPapelera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarPapelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPapeleraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(cmbBusquedaPapelera, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusquedaPapelera)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPapelera))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombrePapelera)
                            .addComponent(txtURLPapelera)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnLimpiarPapelera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecuperarPapelera)
                        .addGap(76, 76, 76)
                        .addComponent(btnEliminarPapelera)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBusquedaPapelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusquedaPapelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPapelera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombrePapelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtURLPapelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecuperarPapelera)
                    .addComponent(btnEliminarPapelera)
                    .addComponent(btnLimpiarPapelera))
                .addGap(131, 131, 131))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Papelera", jPanel2);

        jMenuArchivo.setText("Archivo");
        jMenuBar1.add(jMenuArchivo);

        jMenuEditar.setText("Editar");
        jMenuBar1.add(jMenuEditar);

        jMenuAcercade.setText("Acerca de");
        jMenuBar1.add(jMenuAcercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SubmenuSalirActionPerformed

    private void btnGuardarSitiosWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSitiosWebActionPerformed
        if (controladorsitiosweb.GuardarSitioWeb(guardarsitiosweb())) {
            JOptionPane.showMessageDialog(rootPane, "Pagina guardada con exito en el sistema");
            LimpiarSitiosWeb();
            modelTableSitiosWeb.setInventario(controladorsitiosweb.ObtenerSitiosWeb());
            modelTableSitiosWeb.fireTableDataChanged();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se pudo guardar el navegador", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarSitiosWebActionPerformed

    public SitiosWeb guardarsitiosweb() {
        if (txtNombreSitiosWeb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo nombres no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNombreSitiosWeb.requestFocus();
            return null;
        }
        if (txtURLSitiosWeb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "No se ah colocado ninguna dirección web", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtURLSitiosWeb.requestFocus();
            return null;
        }
        if (!utilidades.urlValidator(txtURLSitiosWeb.getText())) {
            JOptionPane.showMessageDialog(rootPane, "La direccion web ingresada no es valida", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtURLSitiosWeb.requestFocus();
            return null;
        }
        SitiosWeb sw = new SitiosWeb();
        sw.setNombre(txtNombreSitiosWeb.getText());
        sw.setUrl(txtURLSitiosWeb.getText());
        sw.setFecha_registro(new Date());
        sw.setSeguridad(utilidades.urlSeguridad(txtURLSitiosWeb.getText()));
        sw.setFecha_actualizacion(new Date());
        return sw;
    }
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (sitioswebeditareliminar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay un sitio web para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (sitioswebeditareliminar != null) {
            sitioswebeditareliminar.setNombre(txtNombreSitiosWeb.getText());
            sitioswebeditareliminar.setUrl(txtURLSitiosWeb.getText());
            sitioswebeditareliminar.setFecha_actualizacion(new Date());
            if (controladorsitiosweb.EditarSitioWeb(sitioswebeditareliminar)) {
                JOptionPane.showMessageDialog(rootPane, "Sitio web actualizado");
                LimpiarSitiosWeb();
                sitioswebeditareliminar = null;
                modelTableSitiosWeb.setInventario(controladorsitiosweb.ObtenerSitiosWeb());
                modelTableSitiosWeb.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede actualizar el sitio web", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEnviaraPapeleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviaraPapeleraActionPerformed
        if (sitioswebeditareliminar != null) {
            if (controladorpapelera.GuardarPapelera(guardarpapelera())) {
                JOptionPane.showMessageDialog(rootPane, "Pagina enviada a la papelera");
                LimpiarSitiosWeb();
                modelTablePapelera.setPapelera(controladorpapelera.ObtenerPapelera());
                modelTablePapelera.fireTableDataChanged();
            }
            if (controladorsitiosweb.EliminarSitioWeb(sitioswebeditareliminar)) {
                LimpiarSitiosWeb();
                sitioswebeditareliminar = null;
                modelTableSitiosWeb.setInventario(controladorsitiosweb.ObtenerSitiosWeb());
                modelTableSitiosWeb.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede enviar a la papelera.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay sitio web seleccionado para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviaraPapeleraActionPerformed

    public Papelera guardarpapelera() {
        Papelera pa = new Papelera();
        pa.setNombre(sitioswebeditareliminar.getNombre());
        pa.setUrl(sitioswebeditareliminar.getUrl());
        pa.setFecha_registro(sitioswebeditareliminar.getFecha_registro());
        pa.setSeguridad(sitioswebeditareliminar.getSeguridad());
        pa.setFecha_ultimo_acceso(sitioswebeditareliminar.getFecha_ultimo_acceso());
        pa.setFecha_actualizacion(sitioswebeditareliminar.getFecha_actualizacion());
        return pa;
    }
    private void btnBuscarSitiosWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSitiosWebActionPerformed
        switch (cmbBusquedaSitiosWeb.getSelectedIndex()) {
            case 0://Nombre
                modelTableSitiosWeb.setInventario(controladorsitiosweb.ObtenerSitioWebPrNombre(txtBuscarSitiosWeb.getText()));
                modelTableSitiosWeb.fireTableDataChanged();
                break;
            case 1://URL
                modelTableSitiosWeb.setInventario(controladorsitiosweb.ObtenerSitioWebPorURL(txtBuscarSitiosWeb.getText()));
                modelTableSitiosWeb.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnBuscarSitiosWebActionPerformed

    private void btnNavegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavegarActionPerformed
        utilidades.abirenlace(txtNavegador.getText());
        sitioswebeditareliminar.setFecha_ultimo_acceso(new Date());
        controladorsitiosweb.FechaUltimiAcceso(sitioswebeditareliminar);
        modelTableSitiosWeb.setInventario(controladorsitiosweb.ObtenerSitiosWeb());
        modelTableSitiosWeb.fireTableDataChanged();
    }//GEN-LAST:event_btnNavegarActionPerformed

    private void btnLimpiarSitiosWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarSitiosWebActionPerformed
        LimpiarSitiosWeb();
    }//GEN-LAST:event_btnLimpiarSitiosWebActionPerformed

    public void LimpiarSitiosWeb() {
        txtNombreSitiosWeb.setText("");
        txtURLSitiosWeb.setText("");
        txtNavegador.setText("");
        txtBuscarSitiosWeb.setText("");
    }

    private void btnBuscarPapeleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPapeleraActionPerformed
        switch (cmbBusquedaPapelera.getSelectedIndex()) {
            case 0://Nombre
                modelTablePapelera.setPapelera(controladorpapelera.ObtenerPapeleraPorNombre(txtBusquedaPapelera.getText()));
                modelTablePapelera.fireTableDataChanged();
                break;
            case 1://URL
                modelTablePapelera.setPapelera(controladorpapelera.ObtenerPapeleraPorURL(txtBusquedaPapelera.getText()));
                modelTablePapelera.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnBuscarPapeleraActionPerformed

    private void btnRecuperarPapeleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarPapeleraActionPerformed
        if (papeleraeditareliminar != null) {
            if (controladorsitiosweb.GuardarSitioWeb(recuperarSitios())) {
                JOptionPane.showMessageDialog(rootPane, "Pagina recuperada");
                LimpiarSitiosWeb();
                modelTableSitiosWeb.setInventario(controladorsitiosweb.ObtenerSitiosWeb());
                modelTableSitiosWeb.fireTableDataChanged();
            }
            if (controladorpapelera.EliminarPapelera(papeleraeditareliminar)) {
                LimpiarPapelera();
                papeleraeditareliminar = null;
                modelTablePapelera.setPapelera(controladorpapelera.ObtenerPapelera());
                modelTablePapelera.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede recuperar el sitio", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay sitio web seleccionado para recuperar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRecuperarPapeleraActionPerformed

    public SitiosWeb recuperarSitios() {
        SitiosWeb pa = new SitiosWeb();
        pa.setNombre(papeleraeditareliminar.getNombre());
        pa.setUrl(papeleraeditareliminar.getUrl());
        pa.setFecha_registro(papeleraeditareliminar.getFecha_registro());
        pa.setSeguridad(papeleraeditareliminar.getSeguridad());
        pa.setFecha_ultimo_acceso(papeleraeditareliminar.getFecha_ultimo_acceso());
        pa.setFecha_actualizacion(new Date());
        return pa;
    }
    private void btnEliminarPapeleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPapeleraActionPerformed
        if (papeleraeditareliminar != null) {
            if (controladorpapelera.EliminarPapelera(papeleraeditareliminar)) {
                JOptionPane.showMessageDialog(rootPane, "Sitio eliminado del sistema");
                LimpiarPapelera();
                papeleraeditareliminar = null;
                modelTablePapelera.setPapelera(controladorpapelera.ObtenerPapelera());
                modelTablePapelera.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar el sitio web", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay sitio web seleccionado para eliminar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarPapeleraActionPerformed

    private void btnLimpiarPapeleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPapeleraActionPerformed
        LimpiarPapelera();
    }//GEN-LAST:event_btnLimpiarPapeleraActionPerformed

    private void txtNombreSitiosWebFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreSitiosWebFocusGained
        LimpiarSitiosWeb();
    }//GEN-LAST:event_txtNombreSitiosWebFocusGained

    public void LimpiarPapelera() {
        txtNombrePapelera.setText("");
        txtURLPapelera.setText("");
        txtBusquedaPapelera.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorSitiosWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorSitiosWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorSitiosWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorSitiosWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorSitiosWeb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SubmenuSalir;
    private javax.swing.JButton btnBuscarPapelera;
    private javax.swing.JButton btnBuscarSitiosWeb;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminarPapelera;
    private javax.swing.JButton btnEnviaraPapelera;
    private javax.swing.JButton btnGuardarSitiosWeb;
    private javax.swing.JButton btnLimpiarPapelera;
    private javax.swing.JButton btnLimpiarSitiosWeb;
    private javax.swing.JButton btnNavegar;
    private javax.swing.JButton btnRecuperarPapelera;
    private javax.swing.JComboBox<String> cmbBusquedaPapelera;
    private javax.swing.JComboBox<String> cmbBusquedaSitiosWeb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenuAcercade;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtBuscarSitiosWeb;
    private javax.swing.JTextField txtBusquedaPapelera;
    private javax.swing.JTextField txtNavegador;
    private javax.swing.JTextField txtNombrePapelera;
    private javax.swing.JTextField txtNombreSitiosWeb;
    private javax.swing.JTextField txtURLPapelera;
    private javax.swing.JTextField txtURLSitiosWeb;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clickSitiosWeb(SitiosWeb p) {
        sitioswebeditareliminar = p;
        txtNombreSitiosWeb.setText(sitioswebeditareliminar.getNombre());
        txtURLSitiosWeb.setText(sitioswebeditareliminar.getUrl());
        txtNavegador.setText(sitioswebeditareliminar.getUrl());
    }

    @Override
    public void clickPapelera(Papelera p) {
        papeleraeditareliminar = p;
        txtNombrePapelera.setText(papeleraeditareliminar.getNombre());
        txtURLPapelera.setText(papeleraeditareliminar.getUrl());
    }
}
